version: '4'

services:
  node-start-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker 
      - POSTGRESQL_PASSWORD=docker 
      - POSTGRESQL_DATABASE=nodestart
    mem_limit: 1g
    memswap_limit: 2g